apiVersion: v1
kind: ReplicationController
metadata:
   name: myjavaapp-rc
spec:
   replicas: 2
   selector: 
     app: myjavaapp
     
   template:
     metadata:
       labels:
          app: myjavaapp
          version: 2.6.3
      
     spec:
       containers:
       - name: myjavacontainer
         image: maha4iac/myonlinebooking:2
         ports:
          - containerPort: 8080


























